task :default do
  sh "bundle exec sfrp --build='avr-gcc -Os -mmcu=atmega8 -fdata-sections -ffunction-sections -Wl,--gc-sections'"
  sh 'avr-size Main'
end

task :stack do
  sh "bundle exec sfrp --build='avr-gcc -Os -fstack-usage -mmcu=atmega8 -fdata-sections -ffunction-sections -Wl,--gc-sections'"
  sh 'avr-size Main'
end


task :install => :default do
  sh "sudo avrdude -c avrispmkII -P usb -p m8 -U flash:w:Main:e -v"
end

task :clean do
  sh 'rm -rf ./Main ./output ./*.su'
end
