task :default do
  fstack_opt = `avr-gcc --version`.match(/(\d+)\.(\d+)\.(\d+)/) do |m|
    m[1].to_i >= 4 && m[2].to_i >= 6 ? '-fstack-usage' : ''
  end
  sh "bundle exec sfrp --build='avr-gcc -Os #{fstack_opt} -mmcu=atmega8'"
  sh 'cat main.su'
  sh 'cat Timer.su'
  sh 'cat GPIO.su'
  sh 'cat Main.su'
  sh 'avr-size Main'
end

task :install => :default do
  sh "sudo avrdude -c avrispmkII -P usb -p m8 -U flash:w:Main:e -v"
end

task :clean do
  sh 'rm -rf ./Main ./output ./*.su'
end
