task :default do
  sh "bundle exec sfrp --build='avr-gcc -Os -mmcu=atmega8'"
end

task :install => :default do
  sh "sudo avrdude -c avrispmkII -P usb -p m8 -U flash:w:Main:e -v"
end

task :clean do
  sh 'rm -rf ./Main ./output'
end
